---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.3

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - spec/dummy/db/schema.rb

Naming/FileName:
  Exclude:
    - 'lib/dry-initializer-rails.rb'

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Lambda:
  Exclude:
    - spec/**/*_spec.rb

Style/LambdaCall:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - spec/dummy/db/schema.rb
  
Style/RaiseArgs:
  EnforcedStyle: compact

Style/Semicolon:
  Exclude:
    - spec/**/*_spec.rb

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
