---
language: ruby
cache: bundler
bundler_args: --without benchmarks tools
script:
  - bundle exec rake spec
  - bundle exec rubocop
rvm:
  - 2.3.0
  - 2.6.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
